// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrS9301D8bD0zgSm5ujJ-6XcEu25sRdMQ',
    appId: '1:451059028505:web:0cdaff084eff6f2baf1088',
    messagingSenderId: '451059028505',
    projectId: 'student-information-c1255',
    authDomain: 'student-information-c1255.firebaseapp.com',
    databaseURL: 'https://student-information-c1255-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-information-c1255.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChYc6NfO-2TiiU71bV50lz_DoajR2LjC4',
    appId: '1:451059028505:android:24074c30e6e6b92baf1088',
    messagingSenderId: '451059028505',
    projectId: 'student-information-c1255',
    databaseURL: 'https://student-information-c1255-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-information-c1255.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRHM6fyIptYrwMBbZw7vRaKx516VvlkdQ',
    appId: '1:451059028505:ios:0ee2b6ec55512310af1088',
    messagingSenderId: '451059028505',
    projectId: 'student-information-c1255',
    databaseURL: 'https://student-information-c1255-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-information-c1255.appspot.com',
    iosClientId: '451059028505-cplp91oj17j7en8akmt31t28b7gslufo.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentinfoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRHM6fyIptYrwMBbZw7vRaKx516VvlkdQ',
    appId: '1:451059028505:ios:a16ee59c9d1bbbb9af1088',
    messagingSenderId: '451059028505',
    projectId: 'student-information-c1255',
    databaseURL: 'https://student-information-c1255-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-information-c1255.appspot.com',
    iosClientId: '451059028505-ntu4egihitj718cc9kj9qa7vhr92uc52.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentinfoApp.RunnerTests',
  );
}
